name: Backend Tests (Python)

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        default: '3.12'
        type: string
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ inputs.python-version || '3.12' }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version || '3.12' }}
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install -r requirements.txt
        
    - name: Run Python tests
      run: |
        cd backend
        python -m pytest -v --tb=short || echo "No tests found, skipping..."
