name: Backend Linting (Flake8)

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        default: '3.12'
        type: string
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  flake8:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ inputs.python-version || '3.12' }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version || '3.12' }}
        
    - name: Install Flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-docstrings flake8-import-order flake8-bugbear
        
    - name: Run Flake8
      run: |
        cd backend
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
